// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5yvAAS5-v8CdxYbYoiroQAFcvZmjHfkY',
    appId: '1:382029156647:web:bc756c8071f3aa5b525902',
    messagingSenderId: '382029156647',
    projectId: 'flutterstage-b8997',
    authDomain: 'flutterstage-b8997.firebaseapp.com',
    databaseURL: 'https://flutterstage-b8997-default-rtdb.firebaseio.com',
    storageBucket: 'flutterstage-b8997.firebasestorage.app',
    measurementId: 'G-4TMY17M19C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsR6Z8EaURQhJVYQ--aDER7cn2dHF8QiM',
    appId: '1:382029156647:android:2fa9331fbf58b02b525902',
    messagingSenderId: '382029156647',
    projectId: 'flutterstage-b8997',
    databaseURL: 'https://flutterstage-b8997-default-rtdb.firebaseio.com',
    storageBucket: 'flutterstage-b8997.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVrau26CfzHwSY7mg2FiQxz09jmGsYrl4',
    appId: '1:382029156647:ios:ee75219a738626cc525902',
    messagingSenderId: '382029156647',
    projectId: 'flutterstage-b8997',
    databaseURL: 'https://flutterstage-b8997-default-rtdb.firebaseio.com',
    storageBucket: 'flutterstage-b8997.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVrau26CfzHwSY7mg2FiQxz09jmGsYrl4',
    appId: '1:382029156647:ios:ee75219a738626cc525902',
    messagingSenderId: '382029156647',
    projectId: 'flutterstage-b8997',
    databaseURL: 'https://flutterstage-b8997-default-rtdb.firebaseio.com',
    storageBucket: 'flutterstage-b8997.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5yvAAS5-v8CdxYbYoiroQAFcvZmjHfkY',
    appId: '1:382029156647:web:84453a08dcbe4c1f525902',
    messagingSenderId: '382029156647',
    projectId: 'flutterstage-b8997',
    authDomain: 'flutterstage-b8997.firebaseapp.com',
    databaseURL: 'https://flutterstage-b8997-default-rtdb.firebaseio.com',
    storageBucket: 'flutterstage-b8997.firebasestorage.app',
    measurementId: 'G-1TKZ9GYRMG',
  );
}
